//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpEducationBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string Url2 { get; set; }
        public string Tag { get; set; }
        public string Tag2 { get; set; }
        public Nullable<long> Access { get; set; }
        public string Author { get; set; }
        public string Year { get; set; }
        public Nullable<long> Rating { get; set; }
        public Nullable<long> Downloads { get; set; }
    }
}
